// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxWLk4onnZ6GUv-xQZZ7XQqVq045Qwl9I',
    appId: '1:1084362165063:web:c0ee7b0c39f2e590985a62',
    messagingSenderId: '1084362165063',
    projectId: 'bus-management-660f7',
    authDomain: 'bus-management-660f7.firebaseapp.com',
    databaseURL: 'https://bus-management-660f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-660f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4arWnvy42c10qQ3cNyQjAE0UZur8As_g',
    appId: '1:1084362165063:android:0f53eabe9acc125b985a62',
    messagingSenderId: '1084362165063',
    projectId: 'bus-management-660f7',
    databaseURL: 'https://bus-management-660f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-660f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4vRb24HKN206gDXI44ZIskjJSMsRjtz0',
    appId: '1:1084362165063:ios:0f82829c3e4c58ec985a62',
    messagingSenderId: '1084362165063',
    projectId: 'bus-management-660f7',
    databaseURL: 'https://bus-management-660f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-660f7.firebasestorage.app',
    iosBundleId: 'com.example.faceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4vRb24HKN206gDXI44ZIskjJSMsRjtz0',
    appId: '1:1084362165063:ios:0f82829c3e4c58ec985a62',
    messagingSenderId: '1084362165063',
    projectId: 'bus-management-660f7',
    databaseURL: 'https://bus-management-660f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-660f7.firebasestorage.app',
    iosBundleId: 'com.example.faceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxWLk4onnZ6GUv-xQZZ7XQqVq045Qwl9I',
    appId: '1:1084362165063:web:c8b19dfa1c398ef2985a62',
    messagingSenderId: '1084362165063',
    projectId: 'bus-management-660f7',
    authDomain: 'bus-management-660f7.firebaseapp.com',
    databaseURL: 'https://bus-management-660f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-660f7.firebasestorage.app',
  );

}